--{{ config(materialized='table')}}

--WITH DateDim AS (
--SELECT DISTINCT TO_CHAR(COUNTER, 'YYYYMMDD')::INT AS DATEKEY, TO_DATE(TO_VARCHAR(COUNTER, 'DD/MM/YYYY'),'DD/MM/YYYY') As Date, DATE_PART(Day, COUNTER) AS Day, DATE_PART(Month, COUNTER) AS Month, DATE_PART(Year, COUNTER) AS Year, DATE_PART(Quarter, COUNTER) AS Quarter, MonthName(TO_DATE(COUNTER)) AS MonthName, DAYNAME(TO_DATE(COUNTER)) AS DayName
--FROM {{ source('DBT_SNOWFLAKE', 'PACKET') }}
--WHERE        (DATEDIFF(day, dbo.Packet.COUNTER, GETDATE()) <= 1095)
--UNION 
--SELECT DISTINCT TO_CHAR(COUNTER, 'YYYYMMDD')::INT AS DATEKEY, TO_DATE(TO_VARCHAR(COUNTER, 'DD/MM/YYYY'),'DD/MM/YYYY') As Date, DATE_PART(Day, COUNTER) AS Day, DATE_PART(Month, COUNTER) AS Month, DATE_PART(Year, COUNTER) AS Year, DATE_PART(Quarter, COUNTER) AS Quarter, MonthName(TO_DATE(COUNTER)) AS MonthName, DAYNAME(TO_DATE(COUNTER)) AS DayName
--FROM {{ source('DBT_SNOWFLAKE', 'ARCHIVEPACKET') }}
--WHERE        (DATEDIFF(day, dbo.ArchivePacket.Date, GETDATE()) <= 1095)
--)

--SELECT * FROM DateDim