WITH ActionUser AS (

SELECT DISTINCT USERNAME
FROM {{ source('DBT_SNOWFLAKE', 'SUPERVISORACTIONS') }}
UNION 
SELECT DISTINCT USERNAME
FROM {{ source('DBT_SNOWFLAKE', 'ARCHIVESUPERVISORACTIONS') }}

)


select 
*
from ActionUser