{{ config(
    materialized='incremental',
    unique_key='DATEKEY'
) }}

WITH DateDim AS (
SELECT DISTINCT TO_CHAR(COUNTER, 'YYYYMMDD')::INT AS DATEKEY, TO_DATE(TO_VARCHAR(COUNTER, 'DD/MM/YYYY'),'DD/MM/YYYY') As Date, DATE_PART(Day, COUNTER) AS Day, DATE_PART(Month, COUNTER) AS Month, DATE_PART(Year, COUNTER) AS Year, DATE_PART(Quarter, COUNTER) AS Quarter, MonthName(TO_DATE(COUNTER)) AS MonthName, DAYNAME(TO_DATE(COUNTER)) AS DayName
FROM {{ source('DBT_SNOWFLAKE', 'PACKET') }}
WHERE (DATEDIFF(day, COUNTER, CURRENT_DATE()) <= 2190)
UNION
SELECT DISTINCT TO_CHAR(COUNTER, 'YYYYMMDD')::INT AS DATEKEY, TO_DATE(TO_VARCHAR(COUNTER, 'DD/MM/YYYY'),'DD/MM/YYYY') As Date, DATE_PART(Day, COUNTER) AS Day, DATE_PART(Month, COUNTER) AS Month, DATE_PART(Year, COUNTER) AS Year, DATE_PART(Quarter, COUNTER) AS Quarter, MonthName(TO_DATE(COUNTER)) AS MonthName, DAYNAME(TO_DATE(COUNTER)) AS DayName
FROM {{ source('DBT_SNOWFLAKE', 'ARCHIVEPACKET') }}
WHERE (DATEDIFF(day, Date, CURRENT_DATE()) <= 2190)
)

SELECT * FROM DateDim

{% if is_incremental() %}
WHERE DATEKEY NOT IN (SELECT DATEKEY FROM {{ this }})
{% endif %}