version: 2

sources:
  - name: UserActions
    database: RAW__FORGE__AOPC
    schema: dbo
    tables:
      - name: SUPERVISORACTIONS
      - name: ARCHIVESUPERVISORACTIONS
      - name: PACKET
      - name: ARCHIVEPACKET
