version: 2

sources:
  - name: DBT_SNOWFLAKE
    database: RAW__FORGE__AOPC
    schema: DBO
    tables:
      - name: SUPERVISORACTIONS
      - name: ARCHIVESUPERVISORACTIONS
      - name: PACKET
      - name: ARCHIVEPACKET
