version: 2

sources:
  - name: DBT_SNOWFLAKE
    database: RAW__FORGE__AOPC
    schema: DBO
    tables:
      - name: SUPERVISORACTIONS
      - name: ARCHIVESUPERVISORACTIONS
      - name: PACKET
      - name: ARCHIVEPACKET
      - name: SITEDIM
      - name: USER_DIM
      - name: ACTIONDIM
      - name: PACKETTYPE
      - name: CUSTOMER
      - name: METAL
      - name: SERVICEDIM
      - name: WEBHALLNOTE
      - name: PACKETADDITIONALSERVICE 
      - name: ARCHIVEPACKETADDITIONALSERVICE 
      - name: PACKETITEM
      - name: ARCHIVEPACKETITEM
   
      
